echo -e 'Begin at : \c' && date
/data_center_01/pipeline/16S_ITS_pipeline_v3.0/script/01_get_singleton_read.py --infile /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/00_data/16S_together.fna --outdir /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/single && echo -e 'This-Work-is-Completed! : \c' && date
/home/snowflake/local/bin/usearch7.0.1090_i86linux32 -sortbysize /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/single/derep.fa -output /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/sorted.fa -minsize 2 && echo -e 'This-Work-is-Completed! : \c' && date
/home/snowflake/local/bin/usearch7.0.1090_i86linux32 -cluster_otus /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/sorted.fa -otus /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/cluster_otus.fa && echo -e 'This-Work-is-Completed! : \c' && date
/data_center_01/pipeline/16S_ITS_pipeline_v3.0/script/01_rename_otu_fasta.py --infile /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/cluster_otus.fa --outfile /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/otus.fa && echo -e 'This-Work-is-Completed! : \c' && date
/home/snowflake/local/bin/usearch7.0.1090_i86linux32 -usearch_global /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/00_data/16S_together.fna -db /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/otus.fa -strand plus -id 0.97 -uc /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/map.uc && echo -e 'This-Work-is-Completed! : \c' && date
/data_center_01/pipeline/16S_ITS_pipeline_v3.0/script/01_uc2otutab.py -i /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/map.uc -o /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/otus_all.txt && echo -e 'This-Work-is-Completed! : \c' && date
/data_center_01/pipeline/16S_ITS_pipeline_v3.0/script/01_otutab2fa.py -i /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/00_data/16S_together.fna -t /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/otus_all.txt -o /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/seqs_all.fa && echo -e 'This-Work-is-Completed! : \c' && date
/data_center_01/pipeline/16S_ITS_pipeline_v3.0/script/01_stat.py -r /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/00_data/16S_together.stat -s /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/single/stat.txt --uc /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/map.uc -o /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/pick_otu_summary.xls && echo -e 'This-Work-is-Completed! : \c' && date
echo -e 'All target finished at : \c' && date
