echo -e 'Begin at : \c' && date
/data_center_01/home/liangzb/.pyenv/versions/2.7.10/bin/pick_rep_set.py -i /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/otus_all.txt -f /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/seqs_all.fa -o /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/alpha_rare/rep_set.fna -m most_abundant && echo -e 'This-Work-is-Completed! : \c' && date
/data_center_01/pipeline/16S_ITS_pipeline_v3.0/script/01_rdp_classfier.py -j /data_center_01/home/NEOLINE/liangzebin/soft/RDPTools/classifier.jar -i /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/alpha_rare/rep_set.fna -d 16S -o /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/alpha_rare/rdp_classifier.txt -c 0.8 --hier_outfile /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/alpha_rare/rdp_hier.txt && echo -e 'This-Work-is-Completed! : \c' && date
/data_center_01/pipeline/16S_ITS_pipeline_v3.0/script/01_transform_rdp_qiime.py -i /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/alpha_rare/rdp_classifier.txt -c 0.8 -o /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/alpha_rare/tax_assignment.txt && echo -e 'This-Work-is-Completed! : \c' && date
/data_center_01/home/liangzb/.pyenv/versions/2.7.10/bin/make_otu_table.py -i /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/otus_all.txt -t /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/alpha_rare/tax_assignment.txt -o /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/alpha_rare/otu_table.biom && echo -e 'This-Work-is-Completed! : \c' && date
/data_center_01/pipeline/16S_ITS_pipeline_v3.0/script/01_multiple_rarefactions.py -r /data_center_01/home/liangzb/.pyenv/versions/2.7.10/bin/multiple_rarefactions.py -i /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/alpha_rare/otu_table.biom -o /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/alpha_rare/rarefaction -m 10 -s 4000 -t /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/pick_otu_summary.xls && echo -e 'This-Work-is-Completed! : \c' && date
/data_center_01/home/liangzb/.pyenv/versions/2.7.10/bin/alpha_diversity.py -i /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/alpha_rare/rarefaction -o /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/alpha_rare/alpha_div --metrics chao1,observed_species && echo -e 'This-Work-is-Completed! : \c' && date
/data_center_01/home/liangzb/.pyenv/versions/2.7.10/bin/collate_alpha.py -i /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/alpha_rare/alpha_div -o /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/alpha_rare/alpha_div_collated && echo -e 'This-Work-is-Completed! : \c' && date
/data_center_01/pipeline/16S_ITS_pipeline_v3.0/script/01_alpha_rare_plot.py -g /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/group1.txt -d /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/alpha_rare/alpha_div_collated -o /data_center_01/pipeline/16S_ITS_pipeline_v3.0/test/01_pick_otu/alpha_rare/alpha_div_collated -a chao1,observed_species && echo -e 'This-Work-is-Completed! : \c' && date
echo -e 'All target finished at : \c' && date
